version: '3.8'
services:
  db:
    build: .
    ports:
      - 1433:1433
    volumes:
      - type: volume
        source: data
        target: /var/opt/mssql/data
      - type: volume
        source: log
        target: /var/opt/mssql/log
      - type: volume
        source: secrets
        target: /var/opt/mssql/secrets
volumes:
  data:
  log:
  secrets:
